### ISSUE TITLE
Melhorar o Código com Uso de Constantes

### ISSUE THREAD

**Issue by codetrindade** [EclesiasteVaz/utils_validators#1]
No código atual, as listas `exceptions `e `letterAllowed `são definidas como variáveis mutáveis. Para garantir maior segurança, performance e evitar alterações acidentais, sugere-se definir estas listas como constantes utilizando a palavra-chave `const`.

**Comment by EclesiasteVaz** [comment]
Muito obrigado  boss,  tratei mesmo agora apois de ler o teu conselho.
